### ISSUE TITLE
Need more detailed installation instructions

### ISSUE THREAD

**Issue by abhi-k9** [stoani89/LaTeX2AI#24]
So, I have built the solution successfully following all the steps mentioned in the current README. However, being a casual Adobe Illustrator user, I am not sure how to proceed further. I have noticed the output files under _samplecode/outputs/forms/Release/_ but when I try to run the _.exe_ it says it needs exactly 6 arguments. Can someone enlighten me further?

**Comment by stoani89** [comment]
I have updated the instructions in `README.md` (commit 4dfc2736f7d75d7334b95d6597f97ba5b4879946). When using your own build you should set the Illustrator plug-in folder to your build directory `../Adobe Illustrator CS6 SDK/sample code/output/win/x64/<Debug/Release>`. This option can be set in Illustrator under `Edit / Preferences / Additional modules and virtual memory` (I only have the German version, so the exact names might vary slightly).

The build folder structure changed with the last commit, so  when you pull the new `master` version, make sure to delete the existing `../Adobe Illustrator CS6 SDK/sample code/output/` to avoid unwanted effects.

**Comment by abhi-k9** [comment]
Thanks for the update. I see that the ```.aip``` file was not being generated due to some errors compiling _(ambiguous overloads etc.)_, probably coming from me using the latest api for Illustrator (2021).
