### ISSUE TITLE
Anfrage für eine Illustrator CC 2018 Version

### ISSUE THREAD

**Issue by F-Toe** [stoani89/LaTeX2AI#40]
Sehr geehrter Herr Steinbrecher, 
vielen Dank für die Mühe, ich bin schon neugierig auf das PlugIn. 
 
Viele Grüße nach München,
Fridtjof Toenniessen

**Comment by stoani89** [comment]
I uploaded a commit (405bb5e) which should work with Illustrator CC 2018. Please try the following debug binaries: [LaTeX2AI_405bb5e_debug_Illustrator2018.zip](https://github.com/stoani89/LaTeX2AI/files/6411539/LaTeX2AI_405bb5e_debug_Illustrator2018.zip)

I don't have an running Illustrator CC 2018 version, so it is not testes, but it should work. @F-Toe Could you run the test suite ![testing_light](https://user-images.githubusercontent.com/171502/102027380-e40db800-3da3-11eb-955b-bfcc8466f087.png) and send me the output?

**Comment by stoani89** [comment]
Fixed with #47
