### ISSUE TITLE
Standalone.cls and related problems

### ISSUE THREAD

**Issue by behinger** [stoani89/LaTeX2AI#43]
Hi!
When I run the script In lllustrator 2021, I get the following error:
```
"This is pdfTeX, Version 3.14159265-2.6-1.40.19 (TeX Live 2018/W32TeX) (preloaded format=pdflatex 2019.3.26)  5 MAY 2021 17:56
entering extended mode
 restricted \write18 enabled.
 file:line:error style messages enabled.
 %&-line parsing enabled.
**LaTeX2AI_item.tex
(./LaTeX2AI_item.tex
LaTeX2e <2018-12-01>
(./LaTeX2AI_header.tex

! LaTeX Error: File `standalone.cls' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: cls)

Enter file name: 
./LaTeX2AI_header.tex:27: Emergency stop.
<read *> 
         
l.27 \KOMAoptions
                 {fontsize=11pt}^^M 
Here is how much of TeX's memory you used:
 14 strings out of 494562
 293 string characters out of 6175863
 52246 words of memory out of 5000000
 3770 multiletter control sequences out of 15000+600000
 3640 words of font info for 14 fonts, out of 8000000 for 9000
 14 hyphenation exceptions out of 8191
 12i,0n,8p,128b,8s stack positions out of 5000i,500n,10000p,200000b,80000s

./LaTeX2AI_header.tex:27:  ==> Fatal error occurred, no output PDF file produce
d!
```

But if I generate a debug folder, I can run the bat-file and the correct pdf is created. (I use the pythagoras example).

I already reinstalled MikTex (this time as a local user, what is recommended) - but what I had noticed, that I needed to manually run the script twice (?) so that MikTex on-the-fly installed the packages. 

------
next I tried running illustrator as Administrator - then the script works, but I get the following error
![grafik](https://user-images.githubusercontent.com/10183650/117172412-15773680-adcc-11eb-80f1-c4d3b51342ec.png)
but the output is generated (jei!)

On further testing, the Administrator error only occurs, if I selected a locked layer. The object is created, but with the error message.

Thus now I think I found a secondary, unrelated bug, and maybe my MikTex installation somehow doesnt like to run under no-admin conditions ;)

**Comment by stoani89** [comment]
The fact that the plugin fails, but the debug batch works is strange. I assume, that you tried again after you got the batch file to work? If I remember correctly, the first time LaTeX requires a missing package, MikTeX installs it on the fly, maybe that causes some problems. I personally use TeXlive and not MikTeX, so I do not have a lot of experience with MikTeX.

Did you check, that the correct images are created when running Illustrator as Administrator? Please try again with [this version](https://github.com/stoani89/LaTeX2AI/files/6436867/LaTeX2AI_0d011f8_release_Illustrator2021.zip), the error output should be more expressive in this case.

**Comment by behinger** [comment]
After running it from administrator, now it works also on normal user. Maybe this helps someone having same problems. For the other bug I will create a new issue. That one is easily reproducible ;)
