### ISSUE TITLE
Request for CC 2017 support

### ISSUE THREAD

**Issue by AymericBr** [stoani89/LaTeX2AI#52]
Would it be possible to "reasonably easily" add CC 2017 support ?
Many thanks

**Comment by stoani89** [comment]
Yes indeed, adapting to different Illustrator versions usually does not require a lot of changes. I uploaded a commit (66507a3) which should work with Illustrator CC 2017. Please try the following debug binaries: 
[LaTeX2AI_66507a3_debug_IllustratorCC2017.zip](https://github.com/stoani89/LaTeX2AI/files/6504323/LaTeX2AI_66507a3_debug_IllustratorCC2017.zip). However, I don't have an running Illustrator CC 2017 version, so this version is not tested. @AymericBr you run the test suite ![testing_light](https://user-images.githubusercontent.com/171502/102027380-e40db800-3da3-11eb-955b-bfcc8466f087.png) and send me the output?

**Comment by AymericBr** [comment]
Works like a charm on Illustrator CC 2017. The test suite returns 169/169 passed test.

**Comment by stoani89** [comment]
That sounds good. I will include the Illustrator CC2017 support in the next release, probably withing the next week. Thanks for using LaTeX2AI, if you encounter any other issues, or have suggestions for improvement, feel free to post them in the issue board.

**Comment by stoani89** [comment]
The new LaTeX2AI version `v0.0.5` supports Illustrator CC2017. You can download the release binaries in the [release section].(https://github.com/stoani89/LaTeX2AI/releases)
