### ISSUE TITLE
Error while loading plug-in

### ISSUE THREAD

**Issue by HkingAuditore** [stoani89/LaTeX2AI#56]
throw this 
![image](https://user-images.githubusercontent.com/25510396/121781375-fcd21b80-cbd6-11eb-9e0f-57a980ac78f5.png)

**Comment by HkingAuditore** [comment]
just forget to install the ghostscript...sorry

**Comment by pengtb** [comment]
I installed Ghostscript but it still throws the error...

**Comment by pengtb** [comment]
> I installed Ghostscript but it still throws the error...
> Does someone know how to fix it?

ok I got it. Ghostscript needs to be installed to CSIDL_PROGRAM_FILES.
